export const WX_LOGIN = 'WX_LOGIN'
export const WX_STEP = 'WX_STEP'
export const STEP = 'STEP'
export const ISSTARTBONUS = 'ISSTARTBONUS'
export const BANNERIMAGES = 'BANNERIMAGES'
export const ANSWER = 'ANSWER'
export const SIGN = 'SIGN'
export const NAVTYPE = 'NAVTYPE'
export const PRIZE = 'PRIZE'
export const LOADINGBAR = 'LOADINGBAR'
export const LOADINGTEXT = 'LOADINGTEXT'
export const TOTALSTEP = 'TOTALSTEP'
export const ISFROMSHARE = 'ISFROMSHARE'

